# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e32a0888ee33a8215f07f058a53d5f054930acb0646887b48df38c6acbb944038edb58dbbe4d2ec77da40e4f054b47efa30f4ce96607fea048e8d4766c85733

test:
  secret_key_base: 4aff464c941f57248d3104a628fd4ebee9231f43335d4aa0e567e41b09e88078942c82c242d183a7087615eaac35e5040b38099dfd83817e7b2cf777de93cf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
